// CREATE AN EMPTY ARRAY AND SAVE IT TO VARIABLE NAMED DATA

// INSERT INTO DATA ARRAY THESE VALUES IN THE SAME ORDER: 10, false, "javascript", null

// INSERT AT THE BEGINNING OF AN ARRAY YOUR NAME

// INSERT YOUR AGE RIGHT AFTER YOUR NAME

// PRINT THE FIRST AND LAST ELEMENT OF DATA ARRAY TO THE CONSOLE, SEPARATE THEM WITH COMMA

// REVERSE THE ORDER OF ALL ITEMS IN ARRAY

// REMOVE ITEMS FROM INDEX 0 TO 2 (INCLUDING 2)

// CREATE A SECOND ARRAY FILLED WITH true AND undefined AND SAVE IT TO VARIABLE CALLED DATA2

// COMBINE ARRAYS DATA AND DATA2 INTO ONE

// REMOVE FROM THE ARRAY ALL FALSY VALUES
