// SELECTING BY TAG

// SELECTING BY ID

// SELECTING BY CLASS

// SELECTING BY ATTRIBUTE

// CREATING ELEMENTS & APPENDING TO DOCUMENT ROOT

// APPENDING ELEMENTS TO OTHER ELEMENTS

// REMOVING ELEMENTS
