let numbers = [2,4,6,8,10]

// USE ONLY WHILE LOOP

// PRINT ALL ELEMENTS FROM ARRAY numbers TO THE CONSOLE

// REVERSE THE ORDER OF ALL ELEMENTS FROM ARRAY numbers

// SUM NATURAL NUMBERS UNTIL THE SUM IS BIGGER OR EQUAL 100, 
// PRINT TO THE CONSOLE HOW MANY NUMBERS WERE SUMMED