// VAR = GLOBAL SCOPE, CAN BE REDECLARED

console.log(name); // IT WILL RETURN UNDEFINED, BUT IT WILL NOT THROW AN ERROR, EVEN IF IT'S NOT YET DECLARED
var name = "Karol";// FIRST DECLARATION AND ASSIGNMENT
var name = "Ajil"; // WE DECLARED AND ASSIGN IT FOR SECOND TIME, IT WILL OVERRIDE THE FIRST ONE
console.log(name);




// LET = LOCAL SCOPE, CAN'T BE REDECLARED

let number = 15;
// let number = 10; // IT WOULD THROW AN ERROR, BECAUSE VARIABLE number IS ALREADY DECLARED

// console.log(age); // IT WOULD THROW AN ERROR, BECAUSE VARIABLE age IS NOT YET DECLARED
let age = 15;
console.log(age);




// CONSTANT, CAN BE ASSIGNED ONLY ONCE

const pi_number = 3.14
// pi_number = 4; // IT WILL THROW AN ERROR, BECAUSE WE TRY TO REASSIGN IT