let name = "Karol";

// CREATE A SWITCH STATEMENT WITH 3 OPTIONS
// IN CASE name IS EQUAL TO "Karol", PRINT TO THE CONSOLE "Hello Karol"
// IN CASE name IS EQUAL TO "Robert", PRINT TO THE CONSOLE "Hello Robert"
// IN ANY OTHER CASE PRINT TO THE CONSOLE "Unknown user"
// CHANGE THE VALUE OF name VARIABLE AND SEE IF STATEMENT WORKS CORRECTLY