// ARRAY METHODS



// SUM ALL THE AGES, NO NEED FOR FUNCTION, SAVE IT IN VARIABLE
// 30 + 30 + 40 + 23 + 32 = 155

// WITH FOR
// WITH REDUCE

// ADD PROPERTY "student" TO EACH OBJECT AND SET ITS VALUE TO TRUE

// FIND THE OLDEST PERSON IN THE ARRAY AND PRINT HER/HIS NAME
